server {
    # The port is set to the server's primary allocation on every start.
    listen 8080;
    server_name _;

    root /home/container/webroot;
    index index.php index.html;
    charset utf-8;

    client_max_body_size 100m;
    add_header X-Frame-Options "SAMEORIGIN";

    # NamelessMC friendly URLs
    location / {
        try_files $uri $uri/ /index.php?route=$uri&$args;
    }

    location ~ \.(tpl|cache|htaccess|mmdb|log)$ {
        return 403;
    }

    location ^~ /node_modules/ {
        return 403;
    }

    location ^~ /scripts/ {
        return 403;
    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        try_files $fastcgi_script_name =404;
        fastcgi_pass unix:/home/container/tmp/php-fpm.sock;
        fastcgi_index index.php;
        include /etc/nginx/fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        fastcgi_param HTTP_PROXY "";
        fastcgi_read_timeout 300;
    }

    # Hide dotfiles such as .env, .git and .htaccess.
    location ~ /\.(?!well-known) {
        deny all;
    }
}
